# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Twiki-Upload
version:      0.3
version_from: lib/Pod/Simple/Wiki/Twiki/Upload.pm
installdirs:  site
requires:
    Data::Dumper:                  0
    File::Find:                    0
    File::Path:                    0
    File::Slurp:                   0
    File::Spec:                    0
    IO::File:                      0
    IO::Scalar:                    0
    Pod::Html:                     0
    Pod::Simple::Wiki:             0
    WWW::TWikiClient:              0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
